FROM golang:1.24.5-alpine AS builder

RUN apk add --no-cache yt-dlp

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o video-service cmd/video-service/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates yt-dlp
WORKDIR /root/
COPY --from=builder /app/video-service .
CMD ["./video-service"]
