// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: video/video.proto

package videoPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoAnalyzerService_StartVideoAnalysis_FullMethodName    = "/video.VideoAnalyzerService/StartVideoAnalysis"
	VideoAnalyzerService_GetAnalysisStatus_FullMethodName     = "/video.VideoAnalyzerService/GetAnalysisStatus"
	VideoAnalyzerService_StreamAnalysisResults_FullMethodName = "/video.VideoAnalyzerService/StreamAnalysisResults"
	VideoAnalyzerService_GetCompleteAnalysis_FullMethodName   = "/video.VideoAnalyzerService/GetCompleteAnalysis"
	VideoAnalyzerService_GetAnalysisChunk_FullMethodName      = "/video.VideoAnalyzerService/GetAnalysisChunk"
)

// VideoAnalyzerServiceClient is the client API for VideoAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoAnalyzerServiceClient interface {
	StartVideoAnalysis(ctx context.Context, in *StartVideoAnalysisRequest, opts ...grpc.CallOption) (*StartVideoAnalysisResponse, error)
	GetAnalysisStatus(ctx context.Context, in *GetAnalysisStatusRequest, opts ...grpc.CallOption) (*GetAnalysisStatusResponse, error)
	StreamAnalysisResults(ctx context.Context, in *StreamAnalysisResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisChunkResult], error)
	GetCompleteAnalysis(ctx context.Context, in *GetCompleteAnalysisRequest, opts ...grpc.CallOption) (*GetCompleteAnalysisResponse, error)
	GetAnalysisChunk(ctx context.Context, in *GetAnalysisChunkRequest, opts ...grpc.CallOption) (*GetAnalysisChunkResponse, error)
}

type videoAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoAnalyzerServiceClient(cc grpc.ClientConnInterface) VideoAnalyzerServiceClient {
	return &videoAnalyzerServiceClient{cc}
}

func (c *videoAnalyzerServiceClient) StartVideoAnalysis(ctx context.Context, in *StartVideoAnalysisRequest, opts ...grpc.CallOption) (*StartVideoAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVideoAnalysisResponse)
	err := c.cc.Invoke(ctx, VideoAnalyzerService_StartVideoAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoAnalyzerServiceClient) GetAnalysisStatus(ctx context.Context, in *GetAnalysisStatusRequest, opts ...grpc.CallOption) (*GetAnalysisStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisStatusResponse)
	err := c.cc.Invoke(ctx, VideoAnalyzerService_GetAnalysisStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoAnalyzerServiceClient) StreamAnalysisResults(ctx context.Context, in *StreamAnalysisResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisChunkResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoAnalyzerService_ServiceDesc.Streams[0], VideoAnalyzerService_StreamAnalysisResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAnalysisResultsRequest, AnalysisChunkResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoAnalyzerService_StreamAnalysisResultsClient = grpc.ServerStreamingClient[AnalysisChunkResult]

func (c *videoAnalyzerServiceClient) GetCompleteAnalysis(ctx context.Context, in *GetCompleteAnalysisRequest, opts ...grpc.CallOption) (*GetCompleteAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompleteAnalysisResponse)
	err := c.cc.Invoke(ctx, VideoAnalyzerService_GetCompleteAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoAnalyzerServiceClient) GetAnalysisChunk(ctx context.Context, in *GetAnalysisChunkRequest, opts ...grpc.CallOption) (*GetAnalysisChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisChunkResponse)
	err := c.cc.Invoke(ctx, VideoAnalyzerService_GetAnalysisChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoAnalyzerServiceServer is the server API for VideoAnalyzerService service.
// All implementations must embed UnimplementedVideoAnalyzerServiceServer
// for forward compatibility.
type VideoAnalyzerServiceServer interface {
	StartVideoAnalysis(context.Context, *StartVideoAnalysisRequest) (*StartVideoAnalysisResponse, error)
	GetAnalysisStatus(context.Context, *GetAnalysisStatusRequest) (*GetAnalysisStatusResponse, error)
	StreamAnalysisResults(*StreamAnalysisResultsRequest, grpc.ServerStreamingServer[AnalysisChunkResult]) error
	GetCompleteAnalysis(context.Context, *GetCompleteAnalysisRequest) (*GetCompleteAnalysisResponse, error)
	GetAnalysisChunk(context.Context, *GetAnalysisChunkRequest) (*GetAnalysisChunkResponse, error)
	mustEmbedUnimplementedVideoAnalyzerServiceServer()
}

// UnimplementedVideoAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoAnalyzerServiceServer struct{}

func (UnimplementedVideoAnalyzerServiceServer) StartVideoAnalysis(context.Context, *StartVideoAnalysisRequest) (*StartVideoAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVideoAnalysis not implemented")
}
func (UnimplementedVideoAnalyzerServiceServer) GetAnalysisStatus(context.Context, *GetAnalysisStatusRequest) (*GetAnalysisStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalysisStatus not implemented")
}
func (UnimplementedVideoAnalyzerServiceServer) StreamAnalysisResults(*StreamAnalysisResultsRequest, grpc.ServerStreamingServer[AnalysisChunkResult]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAnalysisResults not implemented")
}
func (UnimplementedVideoAnalyzerServiceServer) GetCompleteAnalysis(context.Context, *GetCompleteAnalysisRequest) (*GetCompleteAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompleteAnalysis not implemented")
}
func (UnimplementedVideoAnalyzerServiceServer) GetAnalysisChunk(context.Context, *GetAnalysisChunkRequest) (*GetAnalysisChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalysisChunk not implemented")
}
func (UnimplementedVideoAnalyzerServiceServer) mustEmbedUnimplementedVideoAnalyzerServiceServer() {}
func (UnimplementedVideoAnalyzerServiceServer) testEmbeddedByValue()                              {}

// UnsafeVideoAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoAnalyzerServiceServer will
// result in compilation errors.
type UnsafeVideoAnalyzerServiceServer interface {
	mustEmbedUnimplementedVideoAnalyzerServiceServer()
}

func RegisterVideoAnalyzerServiceServer(s grpc.ServiceRegistrar, srv VideoAnalyzerServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoAnalyzerService_ServiceDesc, srv)
}

func _VideoAnalyzerService_StartVideoAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVideoAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAnalyzerServiceServer).StartVideoAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoAnalyzerService_StartVideoAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAnalyzerServiceServer).StartVideoAnalysis(ctx, req.(*StartVideoAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoAnalyzerService_GetAnalysisStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAnalyzerServiceServer).GetAnalysisStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoAnalyzerService_GetAnalysisStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAnalyzerServiceServer).GetAnalysisStatus(ctx, req.(*GetAnalysisStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoAnalyzerService_StreamAnalysisResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAnalysisResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoAnalyzerServiceServer).StreamAnalysisResults(m, &grpc.GenericServerStream[StreamAnalysisResultsRequest, AnalysisChunkResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoAnalyzerService_StreamAnalysisResultsServer = grpc.ServerStreamingServer[AnalysisChunkResult]

func _VideoAnalyzerService_GetCompleteAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompleteAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAnalyzerServiceServer).GetCompleteAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoAnalyzerService_GetCompleteAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAnalyzerServiceServer).GetCompleteAnalysis(ctx, req.(*GetCompleteAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoAnalyzerService_GetAnalysisChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAnalyzerServiceServer).GetAnalysisChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoAnalyzerService_GetAnalysisChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAnalyzerServiceServer).GetAnalysisChunk(ctx, req.(*GetAnalysisChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoAnalyzerService_ServiceDesc is the grpc.ServiceDesc for VideoAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoAnalyzerService",
	HandlerType: (*VideoAnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartVideoAnalysis",
			Handler:    _VideoAnalyzerService_StartVideoAnalysis_Handler,
		},
		{
			MethodName: "GetAnalysisStatus",
			Handler:    _VideoAnalyzerService_GetAnalysisStatus_Handler,
		},
		{
			MethodName: "GetCompleteAnalysis",
			Handler:    _VideoAnalyzerService_GetCompleteAnalysis_Handler,
		},
		{
			MethodName: "GetAnalysisChunk",
			Handler:    _VideoAnalyzerService_GetAnalysisChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAnalysisResults",
			Handler:       _VideoAnalyzerService_StreamAnalysisResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "video/video.proto",
}
