// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: video/video.proto

package videoPb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type AnalysisStatus int32

const (
	AnalysisStatus_ANALYSIS_STATUS_PENDING    AnalysisStatus = 0
	AnalysisStatus_ANALYSIS_STATUS_PROCESSING AnalysisStatus = 1
	AnalysisStatus_ANALYSIS_STATUS_STREAMING  AnalysisStatus = 2 // Results available while processing continues
	AnalysisStatus_ANALYSIS_STATUS_COMPLETED  AnalysisStatus = 3
	AnalysisStatus_ANALYSIS_STATUS_FAILED     AnalysisStatus = 4
	AnalysisStatus_ANALYSIS_STATUS_CANCELLED  AnalysisStatus = 5
)

// Enum value maps for AnalysisStatus.
var (
	AnalysisStatus_name = map[int32]string{
		0: "ANALYSIS_STATUS_PENDING",
		1: "ANALYSIS_STATUS_PROCESSING",
		2: "ANALYSIS_STATUS_STREAMING",
		3: "ANALYSIS_STATUS_COMPLETED",
		4: "ANALYSIS_STATUS_FAILED",
		5: "ANALYSIS_STATUS_CANCELLED",
	}
	AnalysisStatus_value = map[string]int32{
		"ANALYSIS_STATUS_PENDING":    0,
		"ANALYSIS_STATUS_PROCESSING": 1,
		"ANALYSIS_STATUS_STREAMING":  2,
		"ANALYSIS_STATUS_COMPLETED":  3,
		"ANALYSIS_STATUS_FAILED":     4,
		"ANALYSIS_STATUS_CANCELLED":  5,
	}
)

func (x AnalysisStatus) Enum() *AnalysisStatus {
	p := new(AnalysisStatus)
	*p = x
	return p
}

func (x AnalysisStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[0].Descriptor()
}

func (AnalysisStatus) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[0]
}

func (x AnalysisStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisStatus.Descriptor instead.
func (AnalysisStatus) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{0}
}

type ChunkStatus int32

const (
	ChunkStatus_CHUNK_STATUS_PENDING          ChunkStatus = 0
	ChunkStatus_CHUNK_STATUS_EXTRACTING_AUDIO ChunkStatus = 1
	ChunkStatus_CHUNK_STATUS_TRANSCRIBING     ChunkStatus = 2
	ChunkStatus_CHUNK_STATUS_ANALYZING        ChunkStatus = 3
	ChunkStatus_CHUNK_STATUS_COMPLETED        ChunkStatus = 4
	ChunkStatus_CHUNK_STATUS_FAILED           ChunkStatus = 5
)

// Enum value maps for ChunkStatus.
var (
	ChunkStatus_name = map[int32]string{
		0: "CHUNK_STATUS_PENDING",
		1: "CHUNK_STATUS_EXTRACTING_AUDIO",
		2: "CHUNK_STATUS_TRANSCRIBING",
		3: "CHUNK_STATUS_ANALYZING",
		4: "CHUNK_STATUS_COMPLETED",
		5: "CHUNK_STATUS_FAILED",
	}
	ChunkStatus_value = map[string]int32{
		"CHUNK_STATUS_PENDING":          0,
		"CHUNK_STATUS_EXTRACTING_AUDIO": 1,
		"CHUNK_STATUS_TRANSCRIBING":     2,
		"CHUNK_STATUS_ANALYZING":        3,
		"CHUNK_STATUS_COMPLETED":        4,
		"CHUNK_STATUS_FAILED":           5,
	}
)

func (x ChunkStatus) Enum() *ChunkStatus {
	p := new(ChunkStatus)
	*p = x
	return p
}

func (x ChunkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[1].Descriptor()
}

func (ChunkStatus) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[1]
}

func (x ChunkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkStatus.Descriptor instead.
func (ChunkStatus) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{1}
}

type AIProvider int32

const (
	AIProvider_AI_PROVIDER_FREE   AIProvider = 0
	AIProvider_AI_PROVIDER_OPENAI AIProvider = 1
	AIProvider_AI_PROVIDER_CLAUDE AIProvider = 2
	AIProvider_AI_PROVIDER_GEMINI AIProvider = 3
)

// Enum value maps for AIProvider.
var (
	AIProvider_name = map[int32]string{
		0: "AI_PROVIDER_FREE",
		1: "AI_PROVIDER_OPENAI",
		2: "AI_PROVIDER_CLAUDE",
		3: "AI_PROVIDER_GEMINI",
	}
	AIProvider_value = map[string]int32{
		"AI_PROVIDER_FREE":   0,
		"AI_PROVIDER_OPENAI": 1,
		"AI_PROVIDER_CLAUDE": 2,
		"AI_PROVIDER_GEMINI": 3,
	}
)

func (x AIProvider) Enum() *AIProvider {
	p := new(AIProvider)
	*p = x
	return p
}

func (x AIProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AIProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[2].Descriptor()
}

func (AIProvider) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[2]
}

func (x AIProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AIProvider.Descriptor instead.
func (AIProvider) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{2}
}

type AnalysisType int32

const (
	AnalysisType_ANALYSIS_TYPE_TRANSCRIPT AnalysisType = 0
	AnalysisType_ANALYSIS_TYPE_SUMMARY    AnalysisType = 1
	AnalysisType_ANALYSIS_TYPE_TOPICS     AnalysisType = 2
	AnalysisType_ANALYSIS_TYPE_QUESTIONS  AnalysisType = 3
	AnalysisType_ANALYSIS_TYPE_INSIGHTS   AnalysisType = 4
	AnalysisType_ANALYSIS_TYPE_ALL        AnalysisType = 5
)

// Enum value maps for AnalysisType.
var (
	AnalysisType_name = map[int32]string{
		0: "ANALYSIS_TYPE_TRANSCRIPT",
		1: "ANALYSIS_TYPE_SUMMARY",
		2: "ANALYSIS_TYPE_TOPICS",
		3: "ANALYSIS_TYPE_QUESTIONS",
		4: "ANALYSIS_TYPE_INSIGHTS",
		5: "ANALYSIS_TYPE_ALL",
	}
	AnalysisType_value = map[string]int32{
		"ANALYSIS_TYPE_TRANSCRIPT": 0,
		"ANALYSIS_TYPE_SUMMARY":    1,
		"ANALYSIS_TYPE_TOPICS":     2,
		"ANALYSIS_TYPE_QUESTIONS":  3,
		"ANALYSIS_TYPE_INSIGHTS":   4,
		"ANALYSIS_TYPE_ALL":        5,
	}
)

func (x AnalysisType) Enum() *AnalysisType {
	p := new(AnalysisType)
	*p = x
	return p
}

func (x AnalysisType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[3].Descriptor()
}

func (AnalysisType) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[3]
}

func (x AnalysisType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisType.Descriptor instead.
func (AnalysisType) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{3}
}

type QuestionDifficulty int32

const (
	QuestionDifficulty_QUESTION_DIFFICULTY_EASY   QuestionDifficulty = 0
	QuestionDifficulty_QUESTION_DIFFICULTY_MEDIUM QuestionDifficulty = 1
	QuestionDifficulty_QUESTION_DIFFICULTY_HARD   QuestionDifficulty = 2
)

// Enum value maps for QuestionDifficulty.
var (
	QuestionDifficulty_name = map[int32]string{
		0: "QUESTION_DIFFICULTY_EASY",
		1: "QUESTION_DIFFICULTY_MEDIUM",
		2: "QUESTION_DIFFICULTY_HARD",
	}
	QuestionDifficulty_value = map[string]int32{
		"QUESTION_DIFFICULTY_EASY":   0,
		"QUESTION_DIFFICULTY_MEDIUM": 1,
		"QUESTION_DIFFICULTY_HARD":   2,
	}
)

func (x QuestionDifficulty) Enum() *QuestionDifficulty {
	p := new(QuestionDifficulty)
	*p = x
	return p
}

func (x QuestionDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[4].Descriptor()
}

func (QuestionDifficulty) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[4]
}

func (x QuestionDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionDifficulty.Descriptor instead.
func (QuestionDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{4}
}

type QuestionType int32

const (
	QuestionType_QUESTION_TYPE_MULTIPLE_CHOICE QuestionType = 0
	QuestionType_QUESTION_TYPE_TRUE_FALSE      QuestionType = 1
	QuestionType_QUESTION_TYPE_SHORT_ANSWER    QuestionType = 2
	QuestionType_QUESTION_TYPE_ESSAY           QuestionType = 3
	QuestionType_QUESTION_TYPE_CODING          QuestionType = 4
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "QUESTION_TYPE_MULTIPLE_CHOICE",
		1: "QUESTION_TYPE_TRUE_FALSE",
		2: "QUESTION_TYPE_SHORT_ANSWER",
		3: "QUESTION_TYPE_ESSAY",
		4: "QUESTION_TYPE_CODING",
	}
	QuestionType_value = map[string]int32{
		"QUESTION_TYPE_MULTIPLE_CHOICE": 0,
		"QUESTION_TYPE_TRUE_FALSE":      1,
		"QUESTION_TYPE_SHORT_ANSWER":    2,
		"QUESTION_TYPE_ESSAY":           3,
		"QUESTION_TYPE_CODING":          4,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[5].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[5]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{5}
}

type TopicDifficulty int32

const (
	TopicDifficulty_TOPIC_DIFFICULTY_BEGINNER     TopicDifficulty = 0
	TopicDifficulty_TOPIC_DIFFICULTY_INTERMEDIATE TopicDifficulty = 1
	TopicDifficulty_TOPIC_DIFFICULTY_ADVANCED     TopicDifficulty = 2
	TopicDifficulty_TOPIC_DIFFICULTY_EXPERT       TopicDifficulty = 3
)

// Enum value maps for TopicDifficulty.
var (
	TopicDifficulty_name = map[int32]string{
		0: "TOPIC_DIFFICULTY_BEGINNER",
		1: "TOPIC_DIFFICULTY_INTERMEDIATE",
		2: "TOPIC_DIFFICULTY_ADVANCED",
		3: "TOPIC_DIFFICULTY_EXPERT",
	}
	TopicDifficulty_value = map[string]int32{
		"TOPIC_DIFFICULTY_BEGINNER":     0,
		"TOPIC_DIFFICULTY_INTERMEDIATE": 1,
		"TOPIC_DIFFICULTY_ADVANCED":     2,
		"TOPIC_DIFFICULTY_EXPERT":       3,
	}
)

func (x TopicDifficulty) Enum() *TopicDifficulty {
	p := new(TopicDifficulty)
	*p = x
	return p
}

func (x TopicDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[6].Descriptor()
}

func (TopicDifficulty) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[6]
}

func (x TopicDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicDifficulty.Descriptor instead.
func (TopicDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{6}
}

type InsightType int32

const (
	InsightType_INSIGHT_TYPE_KEY_CONCEPT       InsightType = 0
	InsightType_INSIGHT_TYPE_IMPORTANT_FORMULA InsightType = 1
	InsightType_INSIGHT_TYPE_PRACTICAL_TIP     InsightType = 2
	InsightType_INSIGHT_TYPE_COMMON_MISTAKE    InsightType = 3
	InsightType_INSIGHT_TYPE_BEST_PRACTICE     InsightType = 4
)

// Enum value maps for InsightType.
var (
	InsightType_name = map[int32]string{
		0: "INSIGHT_TYPE_KEY_CONCEPT",
		1: "INSIGHT_TYPE_IMPORTANT_FORMULA",
		2: "INSIGHT_TYPE_PRACTICAL_TIP",
		3: "INSIGHT_TYPE_COMMON_MISTAKE",
		4: "INSIGHT_TYPE_BEST_PRACTICE",
	}
	InsightType_value = map[string]int32{
		"INSIGHT_TYPE_KEY_CONCEPT":       0,
		"INSIGHT_TYPE_IMPORTANT_FORMULA": 1,
		"INSIGHT_TYPE_PRACTICAL_TIP":     2,
		"INSIGHT_TYPE_COMMON_MISTAKE":    3,
		"INSIGHT_TYPE_BEST_PRACTICE":     4,
	}
)

func (x InsightType) Enum() *InsightType {
	p := new(InsightType)
	*p = x
	return p
}

func (x InsightType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InsightType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[7].Descriptor()
}

func (InsightType) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[7]
}

func (x InsightType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InsightType.Descriptor instead.
func (InsightType) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{7}
}

// Start video analysis request
type StartVideoAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoTitle    string                 `protobuf:"bytes,3,opt,name=video_title,json=videoTitle,proto3" json:"video_title,omitempty"`
	AiProvider    AIProvider             `protobuf:"varint,4,opt,name=ai_provider,json=aiProvider,proto3,enum=video.AIProvider" json:"ai_provider,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVideoAnalysisRequest) Reset() {
	*x = StartVideoAnalysisRequest{}
	mi := &file_video_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVideoAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVideoAnalysisRequest) ProtoMessage() {}

func (x *StartVideoAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVideoAnalysisRequest.ProtoReflect.Descriptor instead.
func (*StartVideoAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{0}
}

func (x *StartVideoAnalysisRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartVideoAnalysisRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *StartVideoAnalysisRequest) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

func (x *StartVideoAnalysisRequest) GetAiProvider() AIProvider {
	if x != nil {
		return x.AiProvider
	}
	return AIProvider_AI_PROVIDER_FREE
}

func (x *StartVideoAnalysisRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessingOptions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ChunkDurationMinutes    int32                  `protobuf:"varint,1,opt,name=chunk_duration_minutes,json=chunkDurationMinutes,proto3" json:"chunk_duration_minutes,omitempty"`            // Default: 15 minutes
	EnableRealTimeStreaming bool                   `protobuf:"varint,2,opt,name=enable_real_time_streaming,json=enableRealTimeStreaming,proto3" json:"enable_real_time_streaming,omitempty"` // Default: true
	AnalysisTypes           []AnalysisType         `protobuf:"varint,3,rep,packed,name=analysis_types,json=analysisTypes,proto3,enum=video.AnalysisType" json:"analysis_types,omitempty"`
	Language                string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_video_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessingOptions) GetChunkDurationMinutes() int32 {
	if x != nil {
		return x.ChunkDurationMinutes
	}
	return 0
}

func (x *ProcessingOptions) GetEnableRealTimeStreaming() bool {
	if x != nil {
		return x.EnableRealTimeStreaming
	}
	return false
}

func (x *ProcessingOptions) GetAnalysisTypes() []AnalysisType {
	if x != nil {
		return x.AnalysisTypes
	}
	return nil
}

func (x *ProcessingOptions) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type StartVideoAnalysisResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId               string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Status                   AnalysisStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=video.AnalysisStatus" json:"status,omitempty"`
	Message                  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedChunks          int32                  `protobuf:"varint,4,opt,name=estimated_chunks,json=estimatedChunks,proto3" json:"estimated_chunks,omitempty"`
	EstimatedDurationMinutes int32                  `protobuf:"varint,5,opt,name=estimated_duration_minutes,json=estimatedDurationMinutes,proto3" json:"estimated_duration_minutes,omitempty"`
	StreamUrl                string                 `protobuf:"bytes,6,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StartVideoAnalysisResponse) Reset() {
	*x = StartVideoAnalysisResponse{}
	mi := &file_video_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVideoAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVideoAnalysisResponse) ProtoMessage() {}

func (x *StartVideoAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVideoAnalysisResponse.ProtoReflect.Descriptor instead.
func (*StartVideoAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{2}
}

func (x *StartVideoAnalysisResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *StartVideoAnalysisResponse) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_PENDING
}

func (x *StartVideoAnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartVideoAnalysisResponse) GetEstimatedChunks() int32 {
	if x != nil {
		return x.EstimatedChunks
	}
	return 0
}

func (x *StartVideoAnalysisResponse) GetEstimatedDurationMinutes() int32 {
	if x != nil {
		return x.EstimatedDurationMinutes
	}
	return 0
}

func (x *StartVideoAnalysisResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

// Streaming results
type StreamAnalysisResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAnalysisResultsRequest) Reset() {
	*x = StreamAnalysisResultsRequest{}
	mi := &file_video_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAnalysisResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAnalysisResultsRequest) ProtoMessage() {}

func (x *StreamAnalysisResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAnalysisResultsRequest.ProtoReflect.Descriptor instead.
func (*StreamAnalysisResultsRequest) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{3}
}

func (x *StreamAnalysisResultsRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type AnalysisChunkResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId         string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ChunkNumber        int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	TotalChunks        int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Status             ChunkStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=video.ChunkStatus" json:"status,omitempty"`
	ChunkData          *VideoChunk            `protobuf:"bytes,5,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,6,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalysisChunkResult) Reset() {
	*x = AnalysisChunkResult{}
	mi := &file_video_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisChunkResult) ProtoMessage() {}

func (x *AnalysisChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisChunkResult.ProtoReflect.Descriptor instead.
func (*AnalysisChunkResult) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{4}
}

func (x *AnalysisChunkResult) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalysisChunkResult) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *AnalysisChunkResult) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *AnalysisChunkResult) GetStatus() ChunkStatus {
	if x != nil {
		return x.Status
	}
	return ChunkStatus_CHUNK_STATUS_PENDING
}

func (x *AnalysisChunkResult) GetChunkData() *VideoChunk {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *AnalysisChunkResult) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *AnalysisChunkResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Video chunk data
type VideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Transcript    string                 `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Topics        []*Topic               `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty"`
	Questions     []*Question            `protobuf:"bytes,8,rep,name=questions,proto3" json:"questions,omitempty"`
	KeyInsights   []*KeyInsight          `protobuf:"bytes,9,rep,name=key_insights,json=keyInsights,proto3" json:"key_insights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	mi := &file_video_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{5}
}

func (x *VideoChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *VideoChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *VideoChunk) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *VideoChunk) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *VideoChunk) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *VideoChunk) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *VideoChunk) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *VideoChunk) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *VideoChunk) GetKeyInsights() []*KeyInsight {
	if x != nil {
		return x.KeyInsights
	}
	return nil
}

type Topic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	KeyPoints       []string               `protobuf:"bytes,4,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	TimestampStart  string                 `protobuf:"bytes,5,opt,name=timestamp_start,json=timestampStart,proto3" json:"timestamp_start,omitempty"`
	TimestampEnd    string                 `protobuf:"bytes,6,opt,name=timestamp_end,json=timestampEnd,proto3" json:"timestamp_end,omitempty"`
	WhyImportant    string                 `protobuf:"bytes,7,opt,name=why_important,json=whyImportant,proto3" json:"why_important,omitempty"`
	RelatedConcepts []string               `protobuf:"bytes,8,rep,name=related_concepts,json=relatedConcepts,proto3" json:"related_concepts,omitempty"`
	Difficulty      TopicDifficulty        `protobuf:"varint,9,opt,name=difficulty,proto3,enum=video.TopicDifficulty" json:"difficulty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_video_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{6}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Topic) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *Topic) GetTimestampStart() string {
	if x != nil {
		return x.TimestampStart
	}
	return ""
}

func (x *Topic) GetTimestampEnd() string {
	if x != nil {
		return x.TimestampEnd
	}
	return ""
}

func (x *Topic) GetWhyImportant() string {
	if x != nil {
		return x.WhyImportant
	}
	return ""
}

func (x *Topic) GetRelatedConcepts() []string {
	if x != nil {
		return x.RelatedConcepts
	}
	return nil
}

func (x *Topic) GetDifficulty() TopicDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TopicDifficulty_TOPIC_DIFFICULTY_BEGINNER
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId            string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Question           string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer             string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	Difficulty         QuestionDifficulty     `protobuf:"varint,5,opt,name=difficulty,proto3,enum=video.QuestionDifficulty" json:"difficulty,omitempty"`
	Type               QuestionType           `protobuf:"varint,6,opt,name=type,proto3,enum=video.QuestionType" json:"type,omitempty"`
	TimestampReference string                 `protobuf:"bytes,7,opt,name=timestamp_reference,json=timestampReference,proto3" json:"timestamp_reference,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_video_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{7}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Question) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Question) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_QUESTION_DIFFICULTY_EASY
}

func (x *Question) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_MULTIPLE_CHOICE
}

func (x *Question) GetTimestampReference() string {
	if x != nil {
		return x.TimestampReference
	}
	return ""
}

type KeyInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Insight       string                 `protobuf:"bytes,2,opt,name=insight,proto3" json:"insight,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          InsightType            `protobuf:"varint,5,opt,name=type,proto3,enum=video.InsightType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInsight) Reset() {
	*x = KeyInsight{}
	mi := &file_video_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInsight) ProtoMessage() {}

func (x *KeyInsight) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInsight.ProtoReflect.Descriptor instead.
func (*KeyInsight) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{8}
}

func (x *KeyInsight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyInsight) GetInsight() string {
	if x != nil {
		return x.Insight
	}
	return ""
}

func (x *KeyInsight) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *KeyInsight) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *KeyInsight) GetType() InsightType {
	if x != nil {
		return x.Type
	}
	return InsightType_INSIGHT_TYPE_KEY_CONCEPT
}

// Complete analysis response
type GetCompleteAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompleteAnalysisRequest) Reset() {
	*x = GetCompleteAnalysisRequest{}
	mi := &file_video_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompleteAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompleteAnalysisRequest) ProtoMessage() {}

func (x *GetCompleteAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompleteAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetCompleteAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompleteAnalysisRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type GetCompleteAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *VideoAnalysis         `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompleteAnalysisResponse) Reset() {
	*x = GetCompleteAnalysisResponse{}
	mi := &file_video_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompleteAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompleteAnalysisResponse) ProtoMessage() {}

func (x *GetCompleteAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompleteAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetCompleteAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetCompleteAnalysisResponse) GetAnalysis() *VideoAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type VideoAnalysis struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoUrl             string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoTitle           string                 `protobuf:"bytes,4,opt,name=video_title,json=videoTitle,proto3" json:"video_title,omitempty"`
	Status               AnalysisStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=video.AnalysisStatus" json:"status,omitempty"`
	AiProvider           AIProvider             `protobuf:"varint,6,opt,name=ai_provider,json=aiProvider,proto3,enum=video.AIProvider" json:"ai_provider,omitempty"`
	TotalChunks          int32                  `protobuf:"varint,7,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	CompletedChunks      int32                  `protobuf:"varint,8,opt,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	TotalDurationMinutes int32                  `protobuf:"varint,9,opt,name=total_duration_minutes,json=totalDurationMinutes,proto3" json:"total_duration_minutes,omitempty"`
	Chunks               []*VideoChunk          `protobuf:"bytes,10,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Metadata             *AnalysisMetadata      `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VideoAnalysis) Reset() {
	*x = VideoAnalysis{}
	mi := &file_video_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoAnalysis) ProtoMessage() {}

func (x *VideoAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoAnalysis.ProtoReflect.Descriptor instead.
func (*VideoAnalysis) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{11}
}

func (x *VideoAnalysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoAnalysis) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoAnalysis) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoAnalysis) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

func (x *VideoAnalysis) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_PENDING
}

func (x *VideoAnalysis) GetAiProvider() AIProvider {
	if x != nil {
		return x.AiProvider
	}
	return AIProvider_AI_PROVIDER_FREE
}

func (x *VideoAnalysis) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *VideoAnalysis) GetCompletedChunks() int32 {
	if x != nil {
		return x.CompletedChunks
	}
	return 0
}

func (x *VideoAnalysis) GetTotalDurationMinutes() int32 {
	if x != nil {
		return x.TotalDurationMinutes
	}
	return 0
}

func (x *VideoAnalysis) GetChunks() []*VideoChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *VideoAnalysis) GetMetadata() *AnalysisMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VideoAnalysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VideoAnalysis) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VideoAnalysis) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type AnalysisMetadata struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	TotalWords             int64                   `protobuf:"varint,1,opt,name=total_words,json=totalWords,proto3" json:"total_words,omitempty"`
	TotalTopics            int64                   `protobuf:"varint,2,opt,name=total_topics,json=totalTopics,proto3" json:"total_topics,omitempty"`
	TotalQuestions         int64                   `protobuf:"varint,3,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	TotalInsights          int64                   `protobuf:"varint,4,opt,name=total_insights,json=totalInsights,proto3" json:"total_insights,omitempty"`
	DominantLanguage       string                  `protobuf:"bytes,5,opt,name=dominant_language,json=dominantLanguage,proto3" json:"dominant_language,omitempty"`
	DetectedSubjects       []string                `protobuf:"bytes,6,rep,name=detected_subjects,json=detectedSubjects,proto3" json:"detected_subjects,omitempty"`
	DifficultyDistribution *DifficultyDistribution `protobuf:"bytes,7,opt,name=difficulty_distribution,json=difficultyDistribution,proto3" json:"difficulty_distribution,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalysisMetadata) Reset() {
	*x = AnalysisMetadata{}
	mi := &file_video_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisMetadata) ProtoMessage() {}

func (x *AnalysisMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisMetadata.ProtoReflect.Descriptor instead.
func (*AnalysisMetadata) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{12}
}

func (x *AnalysisMetadata) GetTotalWords() int64 {
	if x != nil {
		return x.TotalWords
	}
	return 0
}

func (x *AnalysisMetadata) GetTotalTopics() int64 {
	if x != nil {
		return x.TotalTopics
	}
	return 0
}

func (x *AnalysisMetadata) GetTotalQuestions() int64 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *AnalysisMetadata) GetTotalInsights() int64 {
	if x != nil {
		return x.TotalInsights
	}
	return 0
}

func (x *AnalysisMetadata) GetDominantLanguage() string {
	if x != nil {
		return x.DominantLanguage
	}
	return ""
}

func (x *AnalysisMetadata) GetDetectedSubjects() []string {
	if x != nil {
		return x.DetectedSubjects
	}
	return nil
}

func (x *AnalysisMetadata) GetDifficultyDistribution() *DifficultyDistribution {
	if x != nil {
		return x.DifficultyDistribution
	}
	return nil
}

type DifficultyDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EasyTopics    int32                  `protobuf:"varint,1,opt,name=easy_topics,json=easyTopics,proto3" json:"easy_topics,omitempty"`
	MediumTopics  int32                  `protobuf:"varint,2,opt,name=medium_topics,json=mediumTopics,proto3" json:"medium_topics,omitempty"`
	HardTopics    int32                  `protobuf:"varint,3,opt,name=hard_topics,json=hardTopics,proto3" json:"hard_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifficultyDistribution) Reset() {
	*x = DifficultyDistribution{}
	mi := &file_video_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifficultyDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifficultyDistribution) ProtoMessage() {}

func (x *DifficultyDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifficultyDistribution.ProtoReflect.Descriptor instead.
func (*DifficultyDistribution) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{13}
}

func (x *DifficultyDistribution) GetEasyTopics() int32 {
	if x != nil {
		return x.EasyTopics
	}
	return 0
}

func (x *DifficultyDistribution) GetMediumTopics() int32 {
	if x != nil {
		return x.MediumTopics
	}
	return 0
}

func (x *DifficultyDistribution) GetHardTopics() int32 {
	if x != nil {
		return x.HardTopics
	}
	return 0
}

// Status and chunk requests
type GetAnalysisStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisStatusRequest) Reset() {
	*x = GetAnalysisStatusRequest{}
	mi := &file_video_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisStatusRequest) ProtoMessage() {}

func (x *GetAnalysisStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisStatusRequest) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{14}
}

func (x *GetAnalysisStatusRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type GetAnalysisStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId          string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Status              AnalysisStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=video.AnalysisStatus" json:"status,omitempty"`
	TotalChunks         int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	CompletedChunks     int32                  `protobuf:"varint,4,opt,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	FailedChunks        int32                  `protobuf:"varint,5,opt,name=failed_chunks,json=failedChunks,proto3" json:"failed_chunks,omitempty"`
	ProgressPercentage  int32                  `protobuf:"varint,6,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CurrentStage        string                 `protobuf:"bytes,7,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	EstimatedCompletion string                 `protobuf:"bytes,8,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	ChunkProgress       []*ChunkProgress       `protobuf:"bytes,9,rep,name=chunk_progress,json=chunkProgress,proto3" json:"chunk_progress,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAnalysisStatusResponse) Reset() {
	*x = GetAnalysisStatusResponse{}
	mi := &file_video_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisStatusResponse) ProtoMessage() {}

func (x *GetAnalysisStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisStatusResponse) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{15}
}

func (x *GetAnalysisStatusResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_PENDING
}

func (x *GetAnalysisStatusResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *GetAnalysisStatusResponse) GetCompletedChunks() int32 {
	if x != nil {
		return x.CompletedChunks
	}
	return 0
}

func (x *GetAnalysisStatusResponse) GetFailedChunks() int32 {
	if x != nil {
		return x.FailedChunks
	}
	return 0
}

func (x *GetAnalysisStatusResponse) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *GetAnalysisStatusResponse) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetEstimatedCompletion() string {
	if x != nil {
		return x.EstimatedCompletion
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetChunkProgress() []*ChunkProgress {
	if x != nil {
		return x.ChunkProgress
	}
	return nil
}

type ChunkProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChunkNumber        int32                  `protobuf:"varint,1,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	Status             ChunkStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=video.ChunkStatus" json:"status,omitempty"`
	Stage              string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"` // "extracting_audio", "transcribing", "analyzing", "completed"
	ProgressPercentage int32                  `protobuf:"varint,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChunkProgress) Reset() {
	*x = ChunkProgress{}
	mi := &file_video_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkProgress) ProtoMessage() {}

func (x *ChunkProgress) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkProgress.ProtoReflect.Descriptor instead.
func (*ChunkProgress) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{16}
}

func (x *ChunkProgress) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *ChunkProgress) GetStatus() ChunkStatus {
	if x != nil {
		return x.Status
	}
	return ChunkStatus_CHUNK_STATUS_PENDING
}

func (x *ChunkProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ChunkProgress) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

type GetAnalysisChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisChunkRequest) Reset() {
	*x = GetAnalysisChunkRequest{}
	mi := &file_video_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisChunkRequest) ProtoMessage() {}

func (x *GetAnalysisChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisChunkRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisChunkRequest) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{17}
}

func (x *GetAnalysisChunkRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *GetAnalysisChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type GetAnalysisChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *VideoChunk            `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisChunkResponse) Reset() {
	*x = GetAnalysisChunkResponse{}
	mi := &file_video_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisChunkResponse) ProtoMessage() {}

func (x *GetAnalysisChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisChunkResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisChunkResponse) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{18}
}

func (x *GetAnalysisChunkResponse) GetChunk() *VideoChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_video_video_proto protoreflect.FileDescriptor

const file_video_video_proto_rawDesc = "" +
	"\n" +
	"\x11video/video.proto\x12\x05video\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xda\x01\n" +
	"\x19StartVideoAnalysisRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vvideo_title\x18\x03 \x01(\tR\n" +
	"videoTitle\x122\n" +
	"\vai_provider\x18\x04 \x01(\x0e2\x11.video.AIProviderR\n" +
	"aiProvider\x122\n" +
	"\aoptions\x18\x05 \x01(\v2\x18.video.ProcessingOptionsR\aoptions\"\xde\x01\n" +
	"\x11ProcessingOptions\x124\n" +
	"\x16chunk_duration_minutes\x18\x01 \x01(\x05R\x14chunkDurationMinutes\x12;\n" +
	"\x1aenable_real_time_streaming\x18\x02 \x01(\bR\x17enableRealTimeStreaming\x12:\n" +
	"\x0eanalysis_types\x18\x03 \x03(\x0e2\x13.video.AnalysisTypeR\ranalysisTypes\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\x8e\x02\n" +
	"\x1aStartVideoAnalysisResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.video.AnalysisStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10estimated_chunks\x18\x04 \x01(\x05R\x0festimatedChunks\x12<\n" +
	"\x1aestimated_duration_minutes\x18\x05 \x01(\x05R\x18estimatedDurationMinutes\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x06 \x01(\tR\tstreamUrl\"?\n" +
	"\x1cStreamAnalysisResultsRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"\xca\x02\n" +
	"\x13AnalysisChunkResult\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.video.ChunkStatusR\x06status\x120\n" +
	"\n" +
	"chunk_data\x18\x05 \x01(\v2\x11.video.VideoChunkR\tchunkData\x12/\n" +
	"\x13progress_percentage\x18\x06 \x01(\x05R\x12progressPercentage\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xc9\x02\n" +
	"\n" +
	"VideoChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12$\n" +
	"\x06topics\x18\a \x03(\v2\f.video.TopicR\x06topics\x12-\n" +
	"\tquestions\x18\b \x03(\v2\x0f.video.QuestionR\tquestions\x124\n" +
	"\fkey_insights\x18\t \x03(\v2\x11.video.KeyInsightR\vkeyInsights\"\xc4\x02\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"key_points\x18\x04 \x03(\tR\tkeyPoints\x12'\n" +
	"\x0ftimestamp_start\x18\x05 \x01(\tR\x0etimestampStart\x12#\n" +
	"\rtimestamp_end\x18\x06 \x01(\tR\ftimestampEnd\x12#\n" +
	"\rwhy_important\x18\a \x01(\tR\fwhyImportant\x12)\n" +
	"\x10related_concepts\x18\b \x03(\tR\x0frelatedConcepts\x126\n" +
	"\n" +
	"difficulty\x18\t \x01(\x0e2\x16.video.TopicDifficultyR\n" +
	"difficulty\"\xfe\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x129\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x19.video.QuestionDifficultyR\n" +
	"difficulty\x12'\n" +
	"\x04type\x18\x06 \x01(\x0e2\x13.video.QuestionTypeR\x04type\x12/\n" +
	"\x13timestamp_reference\x18\a \x01(\tR\x12timestampReference\"\x9e\x01\n" +
	"\n" +
	"KeyInsight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\ainsight\x18\x02 \x01(\tR\ainsight\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12&\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.video.InsightTypeR\x04type\"=\n" +
	"\x1aGetCompleteAnalysisRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"O\n" +
	"\x1bGetCompleteAnalysisResponse\x120\n" +
	"\banalysis\x18\x01 \x01(\v2\x14.video.VideoAnalysisR\banalysis\"\xf2\x04\n" +
	"\rVideoAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vvideo_title\x18\x04 \x01(\tR\n" +
	"videoTitle\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.video.AnalysisStatusR\x06status\x122\n" +
	"\vai_provider\x18\x06 \x01(\x0e2\x11.video.AIProviderR\n" +
	"aiProvider\x12!\n" +
	"\ftotal_chunks\x18\a \x01(\x05R\vtotalChunks\x12)\n" +
	"\x10completed_chunks\x18\b \x01(\x05R\x0fcompletedChunks\x124\n" +
	"\x16total_duration_minutes\x18\t \x01(\x05R\x14totalDurationMinutes\x12)\n" +
	"\x06chunks\x18\n" +
	" \x03(\v2\x11.video.VideoChunkR\x06chunks\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.video.AnalysisMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xd8\x02\n" +
	"\x10AnalysisMetadata\x12\x1f\n" +
	"\vtotal_words\x18\x01 \x01(\x03R\n" +
	"totalWords\x12!\n" +
	"\ftotal_topics\x18\x02 \x01(\x03R\vtotalTopics\x12'\n" +
	"\x0ftotal_questions\x18\x03 \x01(\x03R\x0etotalQuestions\x12%\n" +
	"\x0etotal_insights\x18\x04 \x01(\x03R\rtotalInsights\x12+\n" +
	"\x11dominant_language\x18\x05 \x01(\tR\x10dominantLanguage\x12+\n" +
	"\x11detected_subjects\x18\x06 \x03(\tR\x10detectedSubjects\x12V\n" +
	"\x17difficulty_distribution\x18\a \x01(\v2\x1d.video.DifficultyDistributionR\x16difficultyDistribution\"\x7f\n" +
	"\x16DifficultyDistribution\x12\x1f\n" +
	"\veasy_topics\x18\x01 \x01(\x05R\n" +
	"easyTopics\x12#\n" +
	"\rmedium_topics\x18\x02 \x01(\x05R\fmediumTopics\x12\x1f\n" +
	"\vhard_topics\x18\x03 \x01(\x05R\n" +
	"hardTopics\";\n" +
	"\x18GetAnalysisStatusRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"\xa4\x03\n" +
	"\x19GetAnalysisStatusResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.video.AnalysisStatusR\x06status\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12)\n" +
	"\x10completed_chunks\x18\x04 \x01(\x05R\x0fcompletedChunks\x12#\n" +
	"\rfailed_chunks\x18\x05 \x01(\x05R\ffailedChunks\x12/\n" +
	"\x13progress_percentage\x18\x06 \x01(\x05R\x12progressPercentage\x12#\n" +
	"\rcurrent_stage\x18\a \x01(\tR\fcurrentStage\x121\n" +
	"\x14estimated_completion\x18\b \x01(\tR\x13estimatedCompletion\x12;\n" +
	"\x0echunk_progress\x18\t \x03(\v2\x14.video.ChunkProgressR\rchunkProgress\"\xa5\x01\n" +
	"\rChunkProgress\x12!\n" +
	"\fchunk_number\x18\x01 \x01(\x05R\vchunkNumber\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.video.ChunkStatusR\x06status\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x05R\x12progressPercentage\"U\n" +
	"\x17GetAnalysisChunkRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\"C\n" +
	"\x18GetAnalysisChunkResponse\x12'\n" +
	"\x05chunk\x18\x01 \x01(\v2\x11.video.VideoChunkR\x05chunk*\xc6\x01\n" +
	"\x0eAnalysisStatus\x12\x1b\n" +
	"\x17ANALYSIS_STATUS_PENDING\x10\x00\x12\x1e\n" +
	"\x1aANALYSIS_STATUS_PROCESSING\x10\x01\x12\x1d\n" +
	"\x19ANALYSIS_STATUS_STREAMING\x10\x02\x12\x1d\n" +
	"\x19ANALYSIS_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16ANALYSIS_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19ANALYSIS_STATUS_CANCELLED\x10\x05*\xba\x01\n" +
	"\vChunkStatus\x12\x18\n" +
	"\x14CHUNK_STATUS_PENDING\x10\x00\x12!\n" +
	"\x1dCHUNK_STATUS_EXTRACTING_AUDIO\x10\x01\x12\x1d\n" +
	"\x19CHUNK_STATUS_TRANSCRIBING\x10\x02\x12\x1a\n" +
	"\x16CHUNK_STATUS_ANALYZING\x10\x03\x12\x1a\n" +
	"\x16CHUNK_STATUS_COMPLETED\x10\x04\x12\x17\n" +
	"\x13CHUNK_STATUS_FAILED\x10\x05*j\n" +
	"\n" +
	"AIProvider\x12\x14\n" +
	"\x10AI_PROVIDER_FREE\x10\x00\x12\x16\n" +
	"\x12AI_PROVIDER_OPENAI\x10\x01\x12\x16\n" +
	"\x12AI_PROVIDER_CLAUDE\x10\x02\x12\x16\n" +
	"\x12AI_PROVIDER_GEMINI\x10\x03*\xb1\x01\n" +
	"\fAnalysisType\x12\x1c\n" +
	"\x18ANALYSIS_TYPE_TRANSCRIPT\x10\x00\x12\x19\n" +
	"\x15ANALYSIS_TYPE_SUMMARY\x10\x01\x12\x18\n" +
	"\x14ANALYSIS_TYPE_TOPICS\x10\x02\x12\x1b\n" +
	"\x17ANALYSIS_TYPE_QUESTIONS\x10\x03\x12\x1a\n" +
	"\x16ANALYSIS_TYPE_INSIGHTS\x10\x04\x12\x15\n" +
	"\x11ANALYSIS_TYPE_ALL\x10\x05*p\n" +
	"\x12QuestionDifficulty\x12\x1c\n" +
	"\x18QUESTION_DIFFICULTY_EASY\x10\x00\x12\x1e\n" +
	"\x1aQUESTION_DIFFICULTY_MEDIUM\x10\x01\x12\x1c\n" +
	"\x18QUESTION_DIFFICULTY_HARD\x10\x02*\xa2\x01\n" +
	"\fQuestionType\x12!\n" +
	"\x1dQUESTION_TYPE_MULTIPLE_CHOICE\x10\x00\x12\x1c\n" +
	"\x18QUESTION_TYPE_TRUE_FALSE\x10\x01\x12\x1e\n" +
	"\x1aQUESTION_TYPE_SHORT_ANSWER\x10\x02\x12\x17\n" +
	"\x13QUESTION_TYPE_ESSAY\x10\x03\x12\x18\n" +
	"\x14QUESTION_TYPE_CODING\x10\x04*\x8f\x01\n" +
	"\x0fTopicDifficulty\x12\x1d\n" +
	"\x19TOPIC_DIFFICULTY_BEGINNER\x10\x00\x12!\n" +
	"\x1dTOPIC_DIFFICULTY_INTERMEDIATE\x10\x01\x12\x1d\n" +
	"\x19TOPIC_DIFFICULTY_ADVANCED\x10\x02\x12\x1b\n" +
	"\x17TOPIC_DIFFICULTY_EXPERT\x10\x03*\xb0\x01\n" +
	"\vInsightType\x12\x1c\n" +
	"\x18INSIGHT_TYPE_KEY_CONCEPT\x10\x00\x12\"\n" +
	"\x1eINSIGHT_TYPE_IMPORTANT_FORMULA\x10\x01\x12\x1e\n" +
	"\x1aINSIGHT_TYPE_PRACTICAL_TIP\x10\x02\x12\x1f\n" +
	"\x1bINSIGHT_TYPE_COMMON_MISTAKE\x10\x03\x12\x1e\n" +
	"\x1aINSIGHT_TYPE_BEST_PRACTICE\x10\x042\xc6\x05\n" +
	"\x14VideoAnalyzerService\x12x\n" +
	"\x12StartVideoAnalysis\x12 .video.StartVideoAnalysisRequest\x1a!.video.StartVideoAnalysisResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/video/analyze\x12\x88\x01\n" +
	"\x11GetAnalysisStatus\x12\x1f.video.GetAnalysisStatusRequest\x1a .video.GetAnalysisStatusResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/video/analysis/{analysis_id}/status\x12\x8c\x01\n" +
	"\x15StreamAnalysisResults\x12#.video.StreamAnalysisResultsRequest\x1a\x1a.video.AnalysisChunkResult\"0\x82\xd3\xe4\x93\x02*\x12(/api/video/analysis/{analysis_id}/stream0\x01\x12\x87\x01\n" +
	"\x13GetCompleteAnalysis\x12!.video.GetCompleteAnalysisRequest\x1a\".video.GetCompleteAnalysisResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/video/analysis/{analysis_id}\x12\x8f\x01\n" +
	"\x10GetAnalysisChunk\x12\x1e.video.GetAnalysisChunkRequest\x1a\x1f.video.GetAnalysisChunkResponse\":\x82\xd3\xe4\x93\x024\x122/api/video/analysis/{analysis_id}/chunk/{chunk_id}B9Z7github.com/JAAT-1628/clarity-ai/api/proto/video;videoPbb\x06proto3"

var (
	file_video_video_proto_rawDescOnce sync.Once
	file_video_video_proto_rawDescData []byte
)

func file_video_video_proto_rawDescGZIP() []byte {
	file_video_video_proto_rawDescOnce.Do(func() {
		file_video_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_video_proto_rawDesc), len(file_video_video_proto_rawDesc)))
	})
	return file_video_video_proto_rawDescData
}

var file_video_video_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_video_video_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_video_video_proto_goTypes = []any{
	(AnalysisStatus)(0),                  // 0: video.AnalysisStatus
	(ChunkStatus)(0),                     // 1: video.ChunkStatus
	(AIProvider)(0),                      // 2: video.AIProvider
	(AnalysisType)(0),                    // 3: video.AnalysisType
	(QuestionDifficulty)(0),              // 4: video.QuestionDifficulty
	(QuestionType)(0),                    // 5: video.QuestionType
	(TopicDifficulty)(0),                 // 6: video.TopicDifficulty
	(InsightType)(0),                     // 7: video.InsightType
	(*StartVideoAnalysisRequest)(nil),    // 8: video.StartVideoAnalysisRequest
	(*ProcessingOptions)(nil),            // 9: video.ProcessingOptions
	(*StartVideoAnalysisResponse)(nil),   // 10: video.StartVideoAnalysisResponse
	(*StreamAnalysisResultsRequest)(nil), // 11: video.StreamAnalysisResultsRequest
	(*AnalysisChunkResult)(nil),          // 12: video.AnalysisChunkResult
	(*VideoChunk)(nil),                   // 13: video.VideoChunk
	(*Topic)(nil),                        // 14: video.Topic
	(*Question)(nil),                     // 15: video.Question
	(*KeyInsight)(nil),                   // 16: video.KeyInsight
	(*GetCompleteAnalysisRequest)(nil),   // 17: video.GetCompleteAnalysisRequest
	(*GetCompleteAnalysisResponse)(nil),  // 18: video.GetCompleteAnalysisResponse
	(*VideoAnalysis)(nil),                // 19: video.VideoAnalysis
	(*AnalysisMetadata)(nil),             // 20: video.AnalysisMetadata
	(*DifficultyDistribution)(nil),       // 21: video.DifficultyDistribution
	(*GetAnalysisStatusRequest)(nil),     // 22: video.GetAnalysisStatusRequest
	(*GetAnalysisStatusResponse)(nil),    // 23: video.GetAnalysisStatusResponse
	(*ChunkProgress)(nil),                // 24: video.ChunkProgress
	(*GetAnalysisChunkRequest)(nil),      // 25: video.GetAnalysisChunkRequest
	(*GetAnalysisChunkResponse)(nil),     // 26: video.GetAnalysisChunkResponse
	(*timestamppb.Timestamp)(nil),        // 27: google.protobuf.Timestamp
}
var file_video_video_proto_depIdxs = []int32{
	2,  // 0: video.StartVideoAnalysisRequest.ai_provider:type_name -> video.AIProvider
	9,  // 1: video.StartVideoAnalysisRequest.options:type_name -> video.ProcessingOptions
	3,  // 2: video.ProcessingOptions.analysis_types:type_name -> video.AnalysisType
	0,  // 3: video.StartVideoAnalysisResponse.status:type_name -> video.AnalysisStatus
	1,  // 4: video.AnalysisChunkResult.status:type_name -> video.ChunkStatus
	13, // 5: video.AnalysisChunkResult.chunk_data:type_name -> video.VideoChunk
	27, // 6: video.AnalysisChunkResult.completed_at:type_name -> google.protobuf.Timestamp
	14, // 7: video.VideoChunk.topics:type_name -> video.Topic
	15, // 8: video.VideoChunk.questions:type_name -> video.Question
	16, // 9: video.VideoChunk.key_insights:type_name -> video.KeyInsight
	6,  // 10: video.Topic.difficulty:type_name -> video.TopicDifficulty
	4,  // 11: video.Question.difficulty:type_name -> video.QuestionDifficulty
	5,  // 12: video.Question.type:type_name -> video.QuestionType
	7,  // 13: video.KeyInsight.type:type_name -> video.InsightType
	19, // 14: video.GetCompleteAnalysisResponse.analysis:type_name -> video.VideoAnalysis
	0,  // 15: video.VideoAnalysis.status:type_name -> video.AnalysisStatus
	2,  // 16: video.VideoAnalysis.ai_provider:type_name -> video.AIProvider
	13, // 17: video.VideoAnalysis.chunks:type_name -> video.VideoChunk
	20, // 18: video.VideoAnalysis.metadata:type_name -> video.AnalysisMetadata
	27, // 19: video.VideoAnalysis.created_at:type_name -> google.protobuf.Timestamp
	27, // 20: video.VideoAnalysis.updated_at:type_name -> google.protobuf.Timestamp
	27, // 21: video.VideoAnalysis.completed_at:type_name -> google.protobuf.Timestamp
	21, // 22: video.AnalysisMetadata.difficulty_distribution:type_name -> video.DifficultyDistribution
	0,  // 23: video.GetAnalysisStatusResponse.status:type_name -> video.AnalysisStatus
	24, // 24: video.GetAnalysisStatusResponse.chunk_progress:type_name -> video.ChunkProgress
	1,  // 25: video.ChunkProgress.status:type_name -> video.ChunkStatus
	13, // 26: video.GetAnalysisChunkResponse.chunk:type_name -> video.VideoChunk
	8,  // 27: video.VideoAnalyzerService.StartVideoAnalysis:input_type -> video.StartVideoAnalysisRequest
	22, // 28: video.VideoAnalyzerService.GetAnalysisStatus:input_type -> video.GetAnalysisStatusRequest
	11, // 29: video.VideoAnalyzerService.StreamAnalysisResults:input_type -> video.StreamAnalysisResultsRequest
	17, // 30: video.VideoAnalyzerService.GetCompleteAnalysis:input_type -> video.GetCompleteAnalysisRequest
	25, // 31: video.VideoAnalyzerService.GetAnalysisChunk:input_type -> video.GetAnalysisChunkRequest
	10, // 32: video.VideoAnalyzerService.StartVideoAnalysis:output_type -> video.StartVideoAnalysisResponse
	23, // 33: video.VideoAnalyzerService.GetAnalysisStatus:output_type -> video.GetAnalysisStatusResponse
	12, // 34: video.VideoAnalyzerService.StreamAnalysisResults:output_type -> video.AnalysisChunkResult
	18, // 35: video.VideoAnalyzerService.GetCompleteAnalysis:output_type -> video.GetCompleteAnalysisResponse
	26, // 36: video.VideoAnalyzerService.GetAnalysisChunk:output_type -> video.GetAnalysisChunkResponse
	32, // [32:37] is the sub-list for method output_type
	27, // [27:32] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_video_video_proto_init() }
func file_video_video_proto_init() {
	if File_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_video_proto_rawDesc), len(file_video_video_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_video_proto_goTypes,
		DependencyIndexes: file_video_video_proto_depIdxs,
		EnumInfos:         file_video_video_proto_enumTypes,
		MessageInfos:      file_video_video_proto_msgTypes,
	}.Build()
	File_video_video_proto = out.File
	file_video_video_proto_goTypes = nil
	file_video_video_proto_depIdxs = nil
}
